package net.doyouhike.app.bbs.biz.db.green.help;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.doyouhike.app.bbs.biz.db.green.entities.Follow;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOLLOW".
*/
public class FollowDao extends AbstractDao<Follow, String> {

    public static final String TABLENAME = "FOLLOW";

    /**
     * Properties of entity Follow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property User_id = new Property(0, String.class, "user_id", true, "USER_ID");
        public final static Property Follow_each = new Property(1, boolean.class, "follow_each", false, "FOLLOW_EACH");
        public final static Property Nick_name = new Property(2, String.class, "nick_name", false, "NICK_NAME");
        public final static Property Sex = new Property(3, String.class, "sex", false, "SEX");
        public final static Property Avatar = new Property(4, String.class, "avatar", false, "AVATAR");
        public final static Property User_desc = new Property(5, String.class, "user_desc", false, "USER_DESC");
    }


    public FollowDao(DaoConfig config) {
        super(config);
    }
    
    public FollowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOLLOW\" (" + //
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: user_id
                "\"FOLLOW_EACH\" INTEGER NOT NULL ," + // 1: follow_each
                "\"NICK_NAME\" TEXT," + // 2: nick_name
                "\"SEX\" TEXT," + // 3: sex
                "\"AVATAR\" TEXT," + // 4: avatar
                "\"USER_DESC\" TEXT);"); // 5: user_desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOLLOW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Follow entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUser_id());
        stmt.bindLong(2, entity.getFollow_each() ? 1L: 0L);
 
        String nick_name = entity.getNick_name();
        if (nick_name != null) {
            stmt.bindString(3, nick_name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(5, avatar);
        }
 
        String user_desc = entity.getUser_desc();
        if (user_desc != null) {
            stmt.bindString(6, user_desc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Follow entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUser_id());
        stmt.bindLong(2, entity.getFollow_each() ? 1L: 0L);
 
        String nick_name = entity.getNick_name();
        if (nick_name != null) {
            stmt.bindString(3, nick_name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(5, avatar);
        }
 
        String user_desc = entity.getUser_desc();
        if (user_desc != null) {
            stmt.bindString(6, user_desc);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Follow readEntity(Cursor cursor, int offset) {
        Follow entity = new Follow( //
            cursor.getString(offset + 0), // user_id
            cursor.getShort(offset + 1) != 0, // follow_each
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nick_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // avatar
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // user_desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Follow entity, int offset) {
        entity.setUser_id(cursor.getString(offset + 0));
        entity.setFollow_each(cursor.getShort(offset + 1) != 0);
        entity.setNick_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSex(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAvatar(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUser_desc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Follow entity, long rowId) {
        return entity.getUser_id();
    }
    
    @Override
    public String getKey(Follow entity) {
        if(entity != null) {
            return entity.getUser_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Follow entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
